INSERT INTO countries(name) VALUES
 ('Algeria')
,('Angola')
,('Benin')
,('Botswana')
,('Burkina Faso')
,('Burundi')
,('Cabo Verde')
,('Cameroon')
,('Central African Republic')
,('Chad')
,('Comoros')
,('Congo')
,('Côte d''Ivoire')
,('DR Congo')
,('Djibouti')
,('Egypt')
,('Equatorial Guinea')
,('Eritrea')
,('Eswatini')
,('Ethiopia')
,('Gabon')
,('Gambia')
,('Ghana')
,('Guinea')
,('Guinea-Bissau')
,('Kenya')
,('Lesotho')
,('Liberia')
,('Libya')
,('Madagascar')
,('Malawi')
,('Mali')
,('Mauritania')
,('Mauritius')
,('Mayotte')
,('Morocco')
,('Mozambique')
,('Namibia')
,('Niger')
,('Nigeria')
,('Rwanda')
,('Réunion')
,('Saint Helena')
,('Sao Tome & Principe')
,('Senegal')
,('Seychelles')
,('Sierra Leone')
,('Somalia')
,('South Africa')
,('South Sudan')
,('Sudan')
,('Tanzania')
,('Togo')
,('Tunisia')
,('Uganda')
,('Western Sahara')
,('Zambia')
,('Zimbabwe');

