"""Made changes to add delete cascade to fk

Revision ID: 40a1fc3fc0aa
Revises: 7f5f11b693c8
Create Date: 2024-09-12 10:54:22.646119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a1fc3fc0aa'
down_revision: Union[str, None] = '7f5f11b693c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_submissions_submission_id_fkey', 'categories_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'categories_submissions', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('categories_trivias_trivia_id_fkey', 'categories_trivias', type_='foreignkey')
    op.create_foreign_key(None, 'categories_trivias', 'trivias', ['trivia_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('countries_submissions_submission_id_fkey', 'countries_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'countries_submissions', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('countries_trivias_trivia_id_fkey', 'countries_trivias', type_='foreignkey')
    op.create_foreign_key(None, 'countries_trivias', 'trivias', ['trivia_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submission_options_submission_id_fkey', 'submission_options', type_='foreignkey')
    op.create_foreign_key(None, 'submission_options', 'submissions', ['submission_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('trivia_options_trivia_id_fkey', 'trivia_options', type_='foreignkey')
    op.create_foreign_key(None, 'trivia_options', 'trivias', ['trivia_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trivia_options', type_='foreignkey')
    op.create_foreign_key('trivia_options_trivia_id_fkey', 'trivia_options', 'trivias', ['trivia_id'], ['id'])
    op.drop_constraint(None, 'submission_options', type_='foreignkey')
    op.create_foreign_key('submission_options_submission_id_fkey', 'submission_options', 'submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'countries_trivias', type_='foreignkey')
    op.create_foreign_key('countries_trivias_trivia_id_fkey', 'countries_trivias', 'trivias', ['trivia_id'], ['id'])
    op.drop_constraint(None, 'countries_submissions', type_='foreignkey')
    op.create_foreign_key('countries_submissions_submission_id_fkey', 'countries_submissions', 'submissions', ['submission_id'], ['id'])
    op.drop_constraint(None, 'categories_trivias', type_='foreignkey')
    op.create_foreign_key('categories_trivias_trivia_id_fkey', 'categories_trivias', 'trivias', ['trivia_id'], ['id'])
    op.drop_constraint(None, 'categories_submissions', type_='foreignkey')
    op.create_foreign_key('categories_submissions_submission_id_fkey', 'categories_submissions', 'submissions', ['submission_id'], ['id'])
    # ### end Alembic commands ###
