"""Made changes to submission and trivia models

Revision ID: 7f5f11b693c8
Revises: 9b45b7739189
Create Date: 2024-09-12 10:31:22.772528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5f11b693c8'
down_revision: Union[str, None] = '9b45b7739189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'moderator_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'moderator_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
