"""Added unique constraint to trivia questions column

Revision ID: 8e9a39773efc
Revises: 40a1fc3fc0aa
Create Date: 2024-09-16 14:54:32.552949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9a39773efc'
down_revision: Union[str, None] = '40a1fc3fc0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trivias', ['question'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trivias', type_='unique')
    # ### end Alembic commands ###
