"""Added avatar url for mods

Revision ID: 9b45b7739189
Revises: 732caa16a6e8
Create Date: 2024-09-06 12:50:36.675138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b45b7739189'
down_revision: Union[str, None] = '732caa16a6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderators', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderators', 'avatar_url')
    # ### end Alembic commands ###
